import { MigrationInterface, QueryRunner } from 'typeorm';

// NOTE: This migration was hand-written, not generated by
// `typeorm-ts-node-commonjs migration:generate` (no live Postgres instance was
// available in the environment this was authored in). The SQL below was derived
// by reading the installed typeorm package's source (PostgresQueryRunner,
// PostgresDriver, DefaultNamingStrategy) to reproduce column type mapping,
// default-value normalization, enum type naming, and the SHA1-based
// PK_/UQ_ constraint name hashing as closely as possible. It has NOT been
// executed against a real database. Regenerate or verify it against a live
// Postgres instance before relying on it in production.
export class InitialSchema1755000000000 implements MigrationInterface {
  name = 'InitialSchema1755000000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "passwordHash" character varying NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "accounts_platform_enum" AS ENUM('telegram', 'instagram', 'vk', 'youtube', 'linkedin')`,
    );
    await queryRunner.query(
      `CREATE TYPE "accounts_type_enum" AS ENUM('own', 'client', 'public_no_access')`,
    );
    await queryRunner.query(
      `CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "platform" "accounts_platform_enum" NOT NULL, "externalId" character varying NOT NULL, "name" character varying NOT NULL, "avatarUrl" text, "type" "accounts_type_enum" NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "account_credentials" ("accountId" uuid NOT NULL, "encryptedToken" text NOT NULL, "tokenExpiresAt" TIMESTAMP WITH TIME ZONE, "refreshToken" text, CONSTRAINT "PK_e864d70a3409c020cd5de386aab" PRIMARY KEY ("accountId"))`,
    );
    await queryRunner.query(
      `CREATE TABLE "account_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "accountId" uuid NOT NULL, "date" date NOT NULL, "followersCount" integer NOT NULL, "followingCount" integer, "postsCount" integer NOT NULL, "avgReach" double precision, "avgEr" double precision, CONSTRAINT "UQ_c968f26b195ab06394051174514" UNIQUE ("accountId", "date"), CONSTRAINT "PK_304e05ea85c76c06db93b799889" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "posts_type_enum" AS ENUM('post', 'reel', 'carousel', 'video', 'short', 'story')`,
    );
    await queryRunner.query(
      `CREATE TABLE "posts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "accountId" uuid NOT NULL, "externalPostId" character varying NOT NULL, "type" "posts_type_enum" NOT NULL, "publishedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "permalink" text, "thumbnailUrl" text, "caption" text, "likes" integer NOT NULL DEFAULT '0', "comments" integer NOT NULL DEFAULT '0', "shares" integer NOT NULL DEFAULT '0', "views" integer, "reach" integer, "er" double precision, "lastSyncedAt" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "UQ_ed9c3b68bff335be89e0d3f4259" UNIQUE ("accountId", "externalPostId"), CONSTRAINT "PK_2829ac61eff60fcec60d7274b9e" PRIMARY KEY ("id"))`,
    );
    await queryRunner.query(
      `CREATE TYPE "sync_jobs_trigger_enum" AS ENUM('scheduled', 'manual')`,
    );
    await queryRunner.query(
      `CREATE TYPE "sync_jobs_status_enum" AS ENUM('pending', 'running', 'success', 'failed')`,
    );
    await queryRunner.query(
      `CREATE TABLE "sync_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "accountId" uuid NOT NULL, "trigger" "sync_jobs_trigger_enum" NOT NULL, "status" "sync_jobs_status_enum" NOT NULL DEFAULT 'pending', "errorMessage" text, "startedAt" TIMESTAMP WITH TIME ZONE, "finishedAt" TIMESTAMP WITH TIME ZONE, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8586b15058c8811de6286052139" PRIMARY KEY ("id"))`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP TABLE "sync_jobs"`);
    await queryRunner.query(`DROP TYPE "sync_jobs_status_enum"`);
    await queryRunner.query(`DROP TYPE "sync_jobs_trigger_enum"`);
    await queryRunner.query(`DROP TABLE "posts"`);
    await queryRunner.query(`DROP TYPE "posts_type_enum"`);
    await queryRunner.query(`DROP TABLE "account_snapshots"`);
    await queryRunner.query(`DROP TABLE "account_credentials"`);
    await queryRunner.query(`DROP TABLE "accounts"`);
    await queryRunner.query(`DROP TYPE "accounts_type_enum"`);
    await queryRunner.query(`DROP TYPE "accounts_platform_enum"`);
    await queryRunner.query(`DROP TABLE "users"`);
  }
}
